/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    AvatarGroup: typeof import('primevue/avatargroup')['default']
    BranchForm: typeof import('./src/components/Branches/BranchForm.vue')['default']
    BranchList: typeof import('./src/components/Branches/BranchList.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EmployeeForm: typeof import('./src/components/Employees/EmployeeForm.vue')['default']
    EmployeeList: typeof import('./src/components/Employees/EmployeeList.vue')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleForm: typeof import('./src/components/ScheduleForm.vue')['default']
    Select: typeof import('primevue/select')['default']
    ShiftForm: typeof import('./src/components/Shifts/ShiftForm.vue')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
